name: Deploy Comercial Montanha Burguer

on:
  push:
    branches:
      - main 
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          node-size: 20
          cache: 'npm'

      - name: Instalar Dependências
        run: npm ci 

      - name: Compilar Projeto (Build)
        run: npm run build

      - name: Configurar Páginas do GitHub
        uses: actions/configure-pages@v4

      - name: Upload dos Arquivos Compilados
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Publicar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4